# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-07 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='profile_name',
            field=models.CharField(default='Rainbow', max_length=30),
            preserve_default=False,
        ),
    ]
