# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-09 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settingPage', '0002_setting_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='bpmBPM',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='bpmColorPaletteIndex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='bpmHueOffset',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='bpmPartCount',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='brightness',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='confettiHueRange',
            field=models.IntegerField(default=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='confettiPerUpdate',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(default='Description', max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='fps',
            field=models.IntegerField(default=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='glitterChance',
            field=models.IntegerField(default=75),
        ),
        migrations.AddField(
            model_name='profile',
            name='hueUpdateDelay',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='juggleDotCount',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='profile',
            name='juggleDotHueIncrease',
            field=models.IntegerField(default=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='juggleFadeSpeed',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='mode',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='rainbowDeltaHue',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='sinelonBPM',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='profile',
            name='sinelonFadeSpeed',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='New profile', max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
